# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bidirectional.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bidirectional.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x62idirectional.proto\"\x13\n\x02Ok\x12\r\n\x05state\x18\x01 \x01(\t\"\x19\n\x08NewState\x12\r\n\x05state\x18\x01 \x01(\t\"\x17\n\tSubscribe\x12\n\n\x02id\x18\x01 \x01(\t\"\x19\n\x0bUnsubscribe\x12\n\n\x02id\x18\x01 \x01(\t\"\x18\n\nUnubscribe\x12\n\n\x02id\x18\x01 \x01(\t2\x94\x01\n\rBidirectional\x12\x33\n\x16SubscribeStateListener\x12\n.Subscribe\x1a\t.NewState\"\x00\x30\x01\x12-\n\x18UnsubscribeStateListener\x12\n.Subscribe\x1a\x03.Ok\"\x00\x12\x1f\n\x0bUpdateState\x12\t.NewState\x1a\x03.Ok\"\x00\x62\x06proto3'
)




_OK = _descriptor.Descriptor(
  name='Ok',
  full_name='Ok',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='Ok.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=42,
)


_NEWSTATE = _descriptor.Descriptor(
  name='NewState',
  full_name='NewState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='state', full_name='NewState.state', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=69,
)


_SUBSCRIBE = _descriptor.Descriptor(
  name='Subscribe',
  full_name='Subscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Subscribe.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=94,
)


_UNSUBSCRIBE = _descriptor.Descriptor(
  name='Unsubscribe',
  full_name='Unsubscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Unsubscribe.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=121,
)


_UNUBSCRIBE = _descriptor.Descriptor(
  name='Unubscribe',
  full_name='Unubscribe',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Unubscribe.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['Ok'] = _OK
DESCRIPTOR.message_types_by_name['NewState'] = _NEWSTATE
DESCRIPTOR.message_types_by_name['Subscribe'] = _SUBSCRIBE
DESCRIPTOR.message_types_by_name['Unsubscribe'] = _UNSUBSCRIBE
DESCRIPTOR.message_types_by_name['Unubscribe'] = _UNUBSCRIBE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Ok = _reflection.GeneratedProtocolMessageType('Ok', (_message.Message,), {
  'DESCRIPTOR' : _OK,
  '__module__' : 'bidirectional_pb2'
  # @@protoc_insertion_point(class_scope:Ok)
  })
_sym_db.RegisterMessage(Ok)

NewState = _reflection.GeneratedProtocolMessageType('NewState', (_message.Message,), {
  'DESCRIPTOR' : _NEWSTATE,
  '__module__' : 'bidirectional_pb2'
  # @@protoc_insertion_point(class_scope:NewState)
  })
_sym_db.RegisterMessage(NewState)

Subscribe = _reflection.GeneratedProtocolMessageType('Subscribe', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIBE,
  '__module__' : 'bidirectional_pb2'
  # @@protoc_insertion_point(class_scope:Subscribe)
  })
_sym_db.RegisterMessage(Subscribe)

Unsubscribe = _reflection.GeneratedProtocolMessageType('Unsubscribe', (_message.Message,), {
  'DESCRIPTOR' : _UNSUBSCRIBE,
  '__module__' : 'bidirectional_pb2'
  # @@protoc_insertion_point(class_scope:Unsubscribe)
  })
_sym_db.RegisterMessage(Unsubscribe)

Unubscribe = _reflection.GeneratedProtocolMessageType('Unubscribe', (_message.Message,), {
  'DESCRIPTOR' : _UNUBSCRIBE,
  '__module__' : 'bidirectional_pb2'
  # @@protoc_insertion_point(class_scope:Unubscribe)
  })
_sym_db.RegisterMessage(Unubscribe)



_BIDIRECTIONAL = _descriptor.ServiceDescriptor(
  name='Bidirectional',
  full_name='Bidirectional',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=150,
  serialized_end=298,
  methods=[
  _descriptor.MethodDescriptor(
    name='SubscribeStateListener',
    full_name='Bidirectional.SubscribeStateListener',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIBE,
    output_type=_NEWSTATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UnsubscribeStateListener',
    full_name='Bidirectional.UnsubscribeStateListener',
    index=1,
    containing_service=None,
    input_type=_SUBSCRIBE,
    output_type=_OK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateState',
    full_name='Bidirectional.UpdateState',
    index=2,
    containing_service=None,
    input_type=_NEWSTATE,
    output_type=_OK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BIDIRECTIONAL)

DESCRIPTOR.services_by_name['Bidirectional'] = _BIDIRECTIONAL

# @@protoc_insertion_point(module_scope)
