import enum

class DbesState(enum.Enum):
    # Dbest success states
    LOCKED = 1
    FREE_EXCHANGE_AREA_FREE_AUXILIARY_AREA = 2
    FREE_EXCHANGE_AREA_BUSY_AUXILIARY_AREA = 3
    BUSY_EXCHANGE_AREA_FREE_AUXILIARY_AREA = 4
    BUSY_EXCHANGE_AREA_BUSY_AUXILIARY_AREA = 5
    READY_TO_TAKEOFF = 6
    READY_TO_LAND = 7
    READY_TO_DESCENT = 8

    MOVING_DRONE_FROM_EXCHANGE_AREA_TO_AUXILIARY_AREA = 9
    MOVING_DRONE_FROM_AUXILIARY_AREA_TO_EXCHANGE = 10
    MOVING_DRONE_FROM_EXCHANGE_AREA_TO_TAKEOFF_AREA = 11
    MOVING_DRONE_FROM_TAKEOFF_AREA_TO_EXCHANGE_AREA = 12
    MOVING_BATTERY_FROM_COOLING_SOCKET_TO_CHARGE_SOCKET = 13

    EXCHANGING_BATTERY = 14
    PREPARING_TO_LAND = 15
    PREPARING_TO_DESCENT = 16
    RETRACTING_TOP_PLATFORM = 17
    RETRACTING_BOTTOM_PLATFORM = 18

    # Dbest error states
    ERROR_MOVING_DRONE_FROM_EXCHANGE_AREA_TO_AUXILIARY_AREA = 19
    ERROR_MOVING_DRONE_FROM_AUXILIARY_AREA_TO_EXCHANGE = 20
    ERROR_MOVING_DRONE_FROM_EXCHANGE_AREA__TO_TAKEOFF_AREA = 21
    ERROR_MOVING_DRONE_FROM_TAKEOFF_AREA_TO_EXCHANGE_AREA = 22
    
    ERROR_EXCHANGING_BATTERY = 23
    ERROR_RETRACTING_TOP_PLATFORM = 24
    ERROR_RETRACTING_BOTTOM_PLATFORM = 25
    ERROR_PREPARING_TO_DESCENT = 26
    ERROR_PREPARING_TO_LAND = 27

    INCONGRUITY_SENSOR_ON_AUXILIARY_AREA = 28
    INCONGRUITY_SENSOR_OFF_AUXILIARY_AREA = 29
    INCONGRUITY_SENSOR_IN_EXCHANGE_AREA = 30
    INCONGRUITY_SENSOR_OFF_EXCHANGE_AREA = 31
